### ISSUE TITLE
Minor UI fixes

### ISSUE THREAD

**Issue by triloger** [oikos-cash/exchange-v2#1]
Inside the trade section, the menu should show oBNB alongside oUSD and oETH, we must show BNB as the main asset alongside our stablecoin.
 
![image](https://user-images.githubusercontent.com/38734531/120022362-507b1d00-bfba-11eb-9deb-106ab91ac30f.png)

In the synths section, there seems to be an issue with the chart and the entry /upper/lower for all the inverse synths, it’s not recognizing the parameters we set for all the inverse synths in any of the charts.
 
![image](https://user-images.githubusercontent.com/38734531/120022384-57a22b00-bfba-11eb-8e32-37a3254ad403.png)

In this same section, for all the inverse synths, the description is not showing the entry/upper/lower points properly and when you select the tab for it to show the standard synth it takes the customer back to the synth section, it should show the standard chart for that given iSynth instead.

![image](https://user-images.githubusercontent.com/38734531/120031488-def59b80-bfc6-11eb-887f-e73a4811503f.png)
![image](https://user-images.githubusercontent.com/38734531/120031502-e321b900-bfc6-11eb-8b19-c89901d4f9ae.png)

In the trade section for all the inverse synths, they do show the chart properly but there seems to be a UI issue related to the one above in the small space that shows the entry/upper/lower limit as shown in the image below.
 
![image](https://user-images.githubusercontent.com/38734531/120022407-5cff7580-bfba-11eb-8496-6daafec8a494.png)

Inside the assets section, when you click the trade button of any given asset it shows undefined in the last option of the floating menu, as shown in the image below.
 
![image](https://user-images.githubusercontent.com/38734531/120022663-b9629500-bfba-11eb-9537-ca409e4344dc.png)

**Comment by oikos1** [comment]
Inverted assets related issue fixed by [863f66bf](https://github.com/oikos-cash/exchange-v2/commit/863f66bf3c75c8172d6e48e18b19145b3bcf2c0a). Other fixes are still a WIP.

**Comment by oikos1** [comment]
Last bug fixed with: 
[58c81dda.](https://github.com/oikos-cash/exchange-v2/commit/58c81ddadec4d74a333f62099e1f88451ec46298)Closing this.
